name: Daily Check

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  daily-check:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reminder Bot
        run: curl -X POST https://remindersbot-development.onrender.com/run-check
