name: Daily Check

on:
  schedule:
    - cron: "30 17 * * *"  # 19:30 IST during standard time (UTC+2)
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-check:
    runs-on: ubuntu-latest
    steps:
      - name: Call Reminder Bot
        run: curl -X POST https://remindersbot.onrender.com/run-check
